wandb_version: 1

learning_rate:
  desc: null
  value: 2.0e-05
epochs:
  desc: null
  value: 50
batch_size:
  desc: null
  value: 32
stage:
  desc: null
  value: 1
progressive_step:
  desc: null
  value: 5
_wandb:
  desc: null
  value:
    python_version: 3.10.17
    cli_version: 0.17.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1748741208
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 2
      - 13
      - 16
      - 23
      4: 3.10.17
      5: 0.17.7
      8:
      - 5
      13: linux-x86_64
