_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.10.17
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 13
                - 16
                - 23
                - 55
            "4": 3.10.17
            "5": 0.19.11
            "8":
                - 5
            "12": 0.19.11
            "13": linux-x86_64
batch_size:
    value: 32
epochs:
    value: 100000
learning_rate:
    value: 2e-05
stage:
    value: 1
